[package]
name = "core"
version = "0.1.0"
authors = ["zhukai <zhukai@apache.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8"
tokio = { version = "0.2.25", features = ["full"]}
dashmap = "4.0.2"